# frozen_string_literal: true

source 'https://rubygems.org'

gem 'faraday-retry'
gem 'image_optim_pack'
gem 'image_optim'
gem 'jekyll'
gem 'rake'
gem 'tzinfo'
gem 'whatsup_github', git: 'https://github.com/commerce-docs/whatsup_github', tag: 'v1.2.0'
gem 'adobe-comdox-exl-rake-tasks', git: 'https://github.com/commerce-docs/adobe-comdox-exl-rake-tasks.git'
