#
# Copyright 2025 Adobe All Rights Reserved.
# NOTICE:  All information contained herein is, and remains the property of Adobe and its suppliers, if any.
# The intellectual and technical concepts contained herein are proprietary to Adobe and its suppliers and are protected by all applicable intellectual property laws, including trade secret and copyright laws.
# Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained from Adobe.
#
# frozen_string_literal: true

require 'adobe-comdox-exl-rake-tasks'

desc 'Generate an Azure regions map.
  Place the input data file in _jekyll/tmp/azure-regions.json.
  The result will be found in _jekyll/tmp/azure-regions.svg.
  Note, you need Python, PyGMT, and pdf2svg installed.'
task :azure_regions do
  puts 'Generating Azure regions map in PDF: $ '.magenta
  puts 'Note, you need python, pygmt, and pdf2svg installed.'.blue
  sh 'python _scripts/azure_regions.py'
  puts 'Converting PDF to SVG: $ '.magenta
  sh 'pdf2svg tmp/azure-regions.pdf tmp/azure-regions.svg'
end
